#!/usr/bin/env python
"""
Generate UPSTREAM.json — the provenance manifest pinning robosuite's SOARM101
inertials + meshes to the authoritative upstream source:

    TheRobotStudio/SO-ARM100 : Simulation/SO101/so101_new_calib.xml  (+ assets/*.stl)

robosuite REQUIRES a hand-authored arm/gripper split (it cannot consume the
upstream monolithic MJCF as-is: it needs <motor> actuators, eef sites, an FT
sensor, and add_gripper's separate gripper body). So upstream cannot be a code
dependency — instead it owns the *invariant physics* (per-body mass / COM /
inertia and the mesh bytes), and this manifest + the companion drift-guard test
(tests/test_robosuite_private/test_soarm101_upstream_inertials.py) pin robosuite
to it. Bumping upstream = re-run this generator against the new clone, eyeball the
diff (a physics change should have a human in the loop), commit.

lerobot needs no equivalent: its SOARM101/SO101 directory is already a byte-identical
verbatim mirror of SO-ARM100/Simulation/SO101 (URDF md5 308645ed…).

Usage::

    python -m robosuite_private.tools.gen_upstream_manifest /path/to/SO-ARM100
    # default clone path: ~/Documents/dev/SO-ARM100
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import xml.etree.ElementTree as ET

import numpy as np

# Upstream body name -> robosuite (compiled, sans the robot0_ prefix) body name.
# robosuite renames moving_jaw_so101_v1 -> moving_jaw and inserts a massless
# gripper_base mounting frame that has NO upstream counterpart (so it is absent here).
NAME_MAP = {
    "base": "base",
    "shoulder": "shoulder",
    "upper_arm": "upper_arm",
    "lower_arm": "lower_arm",
    "wrist": "wrist",
    "gripper": "gripper",
    "moving_jaw_so101_v1": "moving_jaw",
}

_DEFAULT_CLONE = os.path.expanduser("~/Documents/dev/SO-ARM100")
_REPO = "https://github.com/TheRobotStudio/SO-ARM100.git"


def _parse_inertials(mjcf_path: str) -> dict:
    """{body_name: {mass, com[3], fullinertia[6] (Ixx Iyy Izz Ixy Ixz Iyz)}}."""
    root = ET.parse(mjcf_path).getroot()
    out = {}
    for body in root.iter("body"):
        inert = body.find("inertial")
        if inert is None:
            continue
        com = np.fromstring(inert.get("pos"), sep=" ")
        fi = inert.get("fullinertia")
        if fi is not None:
            I = np.fromstring(fi, sep=" ")
        else:
            d = np.fromstring(inert.get("diaginertia"), sep=" ")
            I = np.array([d[0], d[1], d[2], 0.0, 0.0, 0.0])
        out[body.get("name")] = {
            "mass": float(inert.get("mass")),
            "com": com.tolist(),
            "fullinertia": I.tolist(),
        }
    return out


def main() -> None:
    clone = sys.argv[1] if len(sys.argv) > 1 else _DEFAULT_CLONE
    mjcf = os.path.join(clone, "Simulation/SO101/so101_new_calib.xml")
    assets = os.path.join(clone, "Simulation/SO101/assets")
    if not os.path.exists(mjcf):
        sys.exit(f"upstream MJCF not found: {mjcf}\nClone {_REPO} first.")

    try:
        sha = subprocess.check_output(
            ["git", "-C", clone, "rev-parse", "HEAD"], text=True
        ).strip()
    except Exception:
        sha = "unknown"

    src_inertials = _parse_inertials(mjcf)
    bodies = {}
    for up_name, rs_name in NAME_MAP.items():
        if up_name not in src_inertials:
            sys.exit(f"upstream body {up_name!r} missing from {mjcf}")
        bodies[rs_name] = src_inertials[up_name]

    meshes = {}
    for fn in sorted(os.listdir(assets)):
        if fn.lower().endswith(".stl"):
            with open(os.path.join(assets, fn), "rb") as f:
                meshes[fn] = hashlib.md5(f.read()).hexdigest()

    total_mass = round(sum(b["mass"] for b in bodies.values()), 6)
    manifest = {
        "_comment": "AUTO-GENERATED by robosuite_private/tools/gen_upstream_manifest.py. "
                    "Provenance pin for SOARM101 inertials + meshes. Do not hand-edit.",
        "repo": _REPO,
        "sha": sha,
        "source_file": "Simulation/SO101/so101_new_calib.xml",
        "total_robot_mass_kg": total_mass,
        "bodies": bodies,
        "meshes": meshes,
    }

    out_path = os.path.join(
        os.path.dirname(__file__),
        "..", "..",
        "robosuite/models/assets/robots/SOARM101/UPSTREAM.json",
    )
    out_path = os.path.abspath(out_path)
    with open(out_path, "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    print(f"wrote {out_path}")
    print(f"  sha={sha}  total_mass={total_mass} kg  "
          f"{len(bodies)} bodies  {len(meshes)} meshes")


if __name__ == "__main__":
    main()
